# FROM --platform=linux/amd64 python:3.10

# WORKDIR /app

# # Copy the processing script
# COPY process_pdfs.py .

# # Run the script
# CMD ["python", "process_pdfs.py"] 

FROM python:3.10

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "process_pdfs.py"]